language: ruby
cache: bundler

rvm:
  - 2.4
  - 2.3
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
